name: build and deploy docs

on:
  push:
    branches:
      - master
  pull_request:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: build docs
    runs-on: ubuntu-latest
    steps:
      - name: clean up
        run: |
          rm -rf $HOME/.elan
          rm -rf $HOME/.cache/mathlib

      - uses: actions/checkout@v4

      - name: install elan
        run: |
          set -o pipefail
          curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- --default-toolchain none -y
          echo "$HOME/.elan/bin" >> $GITHUB_PATH

      - name: set default toolchain
        run: |
          elan default $(cat lean-toolchain)

      - name: get cache
        run: lake exe cache get

      - name: build algorithm
        run: env LEAN_ABORT_ON_PANIC=1 lake build

      - name: build doc-gen4
        run: |
          env DISABLE_EQUATIONS=1 lake build doc-gen4

      - name: build import graph
        run: |
          lake exe graph algorithm.html

      - name: generate docs
        run: |
          lake build Algorithm:docs
          lake build Algorithm:docsHeader

      - name: copy import graph
        run: |
          cp algorithm.html ./.lake/build/doc

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './.lake/build/doc'

  deploy:
    if: github.ref == 'refs/heads/master'
    name: deploy docs
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
